import os
import pytest
from app.services.llm.base import LLMProvider, LLMResponse, ToolCall
from app.services.llm.factory import get_llm_provider
from app.services.llm.mock_provider import MockLLMProvider
from app.services.llm.openai_provider import OpenAIProvider
from app.services.llm.gemini_provider import GeminiProvider
from app.agents.orchestrator import BhoomiAgentOrchestrator
from app.agents.tool_registry import ToolRegistry
from app.services.safety.safety_engine import SafetyEngine

@pytest.mark.asyncio
async def test_llm_factory_resolution():
    """Verify that factory respects LLM_PROVIDER and falls back safely to Mock."""
    # 1. Default / Mock
    provider = get_llm_provider("mock")
    assert isinstance(provider, MockLLMProvider)

    # 2. OpenAI provider creation
    os.environ["OPENAI_API_KEY"] = "sk-test-mock-key-12345"
    provider_openai = get_llm_provider("openai")
    assert isinstance(provider_openai, OpenAIProvider)
    assert provider_openai.model == "gpt-4o-mini"
    assert provider_openai.provider_name == "openai"

    # 3. Groq provider creation
    os.environ["GROQ_API_KEY"] = "gsk-test-mock-groq-key-12345"
    provider_groq = get_llm_provider("groq")
    assert isinstance(provider_groq, OpenAIProvider)
    assert provider_groq.provider_name == "groq"
    assert "groq.com" in provider_groq.base_url

    # 4. Gemini provider creation
    os.environ["GEMINI_API_KEY"] = "gemini-test-mock-key-12345"
    provider_gemini = get_llm_provider("gemini")
    assert isinstance(provider_gemini, GeminiProvider)

    # 5. Clean up test env keys
    os.environ.pop("OPENAI_API_KEY", None)
    os.environ.pop("GROQ_API_KEY", None)
    os.environ.pop("GEMINI_API_KEY", None)

@pytest.mark.asyncio
async def test_real_llm_tool_schema_formatting():
    """Verify that ToolRegistry definitions convert into standard function-calling schemas."""
    provider = OpenAIProvider(api_key="test-key")
    tools = ToolRegistry.get_tool_definitions()
    formatted = provider._format_tools(tools)
    
    assert len(formatted) == len(tools)
    first_tool = formatted[0]
    assert first_tool["type"] == "function"
    assert "name" in first_tool["function"]
    assert "description" in first_tool["function"]
    assert "parameters" in first_tool["function"]
    assert first_tool["function"]["name"] == "crop_recommendation"

@pytest.mark.asyncio
async def test_real_llm_graceful_fallback_on_network_error():
    """Verify that network/auth failure does NOT crash the platform; falls back to Mock."""
    # Use invalid key and bad URL to force network error
    failing_provider = OpenAIProvider(api_key="invalid-key", base_url="https://invalid.endpoint.test", timeout=1.0)
    messages = [{"role": "user", "content": "What is the market price of chilli?"}]
    
    resp = await failing_provider.generate_response(messages=messages, system_prompt="Test")
    assert resp is not None
    assert resp.provider == "mock"
    assert "mandi" in resp.content.lower() or "price" in resp.content.lower() or "noted" in resp.content.lower()

@pytest.mark.asyncio
async def test_orchestrator_five_step_tool_loop():
    """
    Verify complete 5-step loop:
    1. Intent detection
    2. Tool selection
    3. Structured argument passing
    4. Deterministic tool execution
    5. SafetyEngine verification
    """
    result = await BhoomiAgentOrchestrator.process_turn(
        farmer_id="farmer_test_turn",
        user_text="What is my expected profit if I cultivate 3 acres of Chilli yielding 10 quintals at 12000 per quintal?"
    )
    
    assert result.response_text is not None
    assert len(result.response_text) > 20
    # Verify deterministic profit card was generated by tool execution
    assert len(result.visual_cards) > 0
    profit_cards = [c for c in result.visual_cards if c.get("card_type") in ["profit_card", "PROFIT_SUMMARY"]]
    assert len(profit_cards) == 1
    # Check that safety engine ran without crashing
    assert "⚠️" not in result.response_text or "Warning" in result.response_text

@pytest.mark.asyncio
async def test_safety_engine_blocks_unsafe_chemicals_in_orchestrator():
    """Verify that SafetyEngine strictly overrides any unsafe LLM advice."""
    unsafe_text = "I recommend spraying Monocrotophos on your chilli plants to control thrips."
    evaluation = SafetyEngine.evaluate(unsafe_text)
    assert evaluation.is_safe is False
    assert evaluation.status == "BLOCK"
    assert any("Monocrotophos" in r and "restricted/banned" in r for r in evaluation.blocked_reasons)
    assert "Safety Alert" in evaluation.modified_text
