from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
import os
import httpx
from app.core.config import settings
from app.core.logging import logger
from app.core.phone_utils import mask_phone_number, normalize_indian_phone

class BaseSMSProvider(ABC):
    """
    Abstract Base Class for SMS delivery transport.
    
    CRITICAL ARCHITECTURE REQUIREMENT:
    The SMS provider receives ONLY the exact text generated by BHOOMI.
    It MUST NEVER generate OTPs.
    It MUST NEVER verify OTPs.
    BHOOMI owns the complete OTP lifecycle.
    """
    @abstractmethod
    async def send_sms(self, phone_number: str, message: str) -> bool:
        """
        Transports the message to the phone number.
        Returns True if the SMS was accepted for delivery by the carrier/gateway, False otherwise.
        """
        pass


class ConsoleSMSProvider(BaseSMSProvider):
    """
    Development, testing, and fallback console transport.
    Logs masked phone and message structure without exposing secrets or leaking plaintext to public callers.
    """
    async def send_sms(self, phone_number: str, message: str) -> bool:
        masked = mask_phone_number(phone_number)
        logger.info(f"[SMS TRANSPORT - CONSOLE] Delivered to {masked}: '{message}'")
        return True


class MockSMSProvider(BaseSMSProvider):
    """
    In-memory SMS provider for automated testing.
    Records all sent messages and allows simulating network or carrier delivery failure.
    """
    def __init__(self):
        self.sent_messages: List[Dict[str, str]] = []
        self.should_fail: bool = False

    def simulate_failure(self, fail: bool = True) -> None:
        self.should_fail = fail

    def clear(self) -> None:
        self.sent_messages.clear()
        self.should_fail = False

    async def send_sms(self, phone_number: str, message: str) -> bool:
        if self.should_fail:
            logger.warning(f"[MOCK SMS TRANSPORT] Simulated carrier failure for {mask_phone_number(phone_number)}")
            return False
        self.sent_messages.append({"phone_number": phone_number, "message": message})
        logger.info(f"[MOCK SMS TRANSPORT] Captured message for {mask_phone_number(phone_number)}")
        return True


class HttpSMSProvider(BaseSMSProvider):
    """
    Generic HTTP / Webhook / REST SMS gateway transport (e.g. MSG91, Fast2SMS, Twilio, or custom SMS gateway).
    
    IMPORTANT: Sends ONLY the pre-generated BHOOMI message via HTTP POST.
    NEVER invokes any third-party OTP generation or third-party OTP verification endpoint.
    """
    def __init__(
        self,
        endpoint_url: Optional[str] = None,
        api_key: Optional[str] = None,
        sender_id: Optional[str] = None,
        auth_token: Optional[str] = None
    ):
        self.endpoint_url = endpoint_url or getattr(settings, "SMS_GATEWAY_URL", None)
        self.api_key = api_key or getattr(settings, "SMS_API_KEY", None)
        self.sender_id = sender_id or getattr(settings, "SMS_SENDER_ID", None) or "BHOOMI"
        self.auth_token = auth_token or getattr(settings, "SMS_AUTH_TOKEN", None)

    async def send_sms(self, phone_number: str, message: str) -> bool:
        if not self.endpoint_url:
            logger.error("HTTP SMS transport misconfigured: SMS_GATEWAY_URL is missing.")
            return False

        headers = {
            "User-Agent": "BHOOMI-FastAPI/2.0",
            "Content-Type": "application/json"
        }
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
            headers["authkey"] = self.api_key
        elif self.auth_token:
            headers["Authorization"] = f"Bearer {self.auth_token}"

        # Standard delivery payload for transactional SMS transport
        payload = {
            "to": phone_number,
            "sender": self.sender_id,
            "message": message,
            "text": message
        }

        masked = mask_phone_number(phone_number)
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(self.endpoint_url, json=payload, headers=headers)
                if 200 <= resp.status_code < 300:
                    logger.info(f"[HTTP SMS TRANSPORT] Accepted for {masked} (HTTP {resp.status_code})")
                    return True
                else:
                    logger.error(
                        f"[HTTP SMS TRANSPORT] Gateway rejected message for {masked}: HTTP {resp.status_code}"
                    )
                    return False
        except Exception as exc:
            logger.error(f"[HTTP SMS TRANSPORT] Network/connection error while delivering to {masked}: {exc}")
            return False


# Singleton mock provider for tests
_mock_provider_instance = MockSMSProvider()

def get_sms_provider() -> BaseSMSProvider:
    """Factory resolving the active SMS transport provider based on configuration."""
    provider_name = (getattr(settings, "SMS_PROVIDER", None) or "console").lower().strip()
    
    if provider_name == "mock":
        return _mock_provider_instance
    elif provider_name in ("http", "generic_http", "msg91", "twilio", "fast2sms"):
        return HttpSMSProvider()
    else:
        return ConsoleSMSProvider()
